ARG BASE_IMAGE=0.3.1 
ARG ALIAS=biop/

FROM ${ALIAS}biop-vnc-base:${BASE_IMAGE}

USER root

# ------------------------------------------------------------------
# StarDist environment (TensorFlow must be installed before stardist)
# ------------------------------------------------------------------
RUN mamba create -n stardist -y python=3.10 \
    && mamba run -n stardist pip install --upgrade pip \
    && mamba run -n stardist pip install "tensorflow[and-cuda]==2.20.*" \
    && mamba run -n stardist pip install stardist ipykernel \
    && mamba clean -a -y

RUN chown -R biop:biop /opt/conda/envs/stardist \
    && chmod -R u+rwX /opt/conda/envs/stardist

RUN chown -R biop:biop /home/biop/ /home/biop/.cache \
    && chmod -R u+rwX,g+rX,o-rwx /home/biop

# for GPU support    
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility

#################################################################
# Container start
USER biop
WORKDIR /home/biop
RUN /opt/conda/envs/stardist/bin/python -m ipykernel install --user --name=stardist --display-name "Python (stardist)"

ENTRYPOINT ["jupyter"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]