ARG ALIAS=biop/
ARG BASE_IMAGE=0.2.2
FROM ${ALIAS}biop-vnc-base:${BASE_IMAGE}

USER root

# install cellpose and download models ( https://cellpose.readthedocs.io/en/latest/models.html )

RUN conda update --all -y \
    && conda create -n dlc \
    && source activate dlc \
    && conda install pytorch cudatoolkit=11.3 -c pytorch -y\
    && conda install -c conda-forge pytables -y 
    
RUN source activate dlc \
    && pip install --pre  "deeplabcut[gui]"

    
USER root

RUN chmod -R a+rwX /home/biop/ \
    && chown -R biop:biop /home/biop/

#################################################################
# Container start
USER biop
WORKDIR /home/biop
ENTRYPOINT ["/usr/local/bin/jupyter"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]
