ARG ALIAS=biop/
ARG BASE_IMAGE=0.3.1
FROM ${ALIAS}biop-vnc-base:${BASE_IMAGE}

USER root

RUN conda create -n yolo python=3.10 -y \
    && conda run -n yolo pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu126 \
    && conda run -n yolo pip install ultralytics ipykernel  \
    && conda clean --all -f -y \
    && conda env export -n "biop" 

RUN chmod -R a+rwX /home/biop/ \
    && chown -R biop:biop /home/biop/

#################################################################
# Container start
USER biop
WORKDIR /home/biop
RUN /opt/conda/envs/yolo/bin/python -m ipykernel install --user --name=yolo --display-name "Python (yolo)"
 
ENTRYPOINT ["jupyter"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]
