ARG ALIAS=biop/
ARG BASE_IMAGE=0.2.1
FROM ${ALIAS}biop-vnc-base:${BASE_IMAGE}

USER root

RUN conda create -n yolo python=3.10 \
    && source activate yolo \
    && pip install ultralytics opencv-python numpy   \
    && conda clean --all -f -y \
    && conda env export -n "biop" 

RUN chmod -R a+rwX /home/biop/ \
    && chown -R biop:biop /home/biop/

#################################################################
# Container start
USER biop
WORKDIR /home/biop
ENTRYPOINT ["/usr/local/bin/jupyter"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]
