ARG BASE_IMAGE=0.3.0
ARG ALIAS=biop/

FROM ${ALIAS}biop-vnc-base:${BASE_IMAGE}

USER root

RUN mamba create -n napari -y python=3.10 \ 
    && mamba run -n napari pip install "napari[all]"  \
    && mamba clean -a -y

RUN chown -R biop:biop /opt/conda/envs/napari \
    && chmod -R u+rwX /opt/conda/envs/napari

# COPY icons folder because of updates since base image was created 
COPY icons/ /opt/icons/

# move icon to the desktop 
RUN mv /opt/icons/desktop-files/specific/napari.desktop /home/biop/Desktop/ \
    && chmod 755 /home/biop/Desktop/napari.desktop \
    && chown biop:biop /home/biop/Desktop/napari.desktop \
    && mv /opt/icons/scripts/* /usr/local/bin/ \
    && chmod 755 /usr/local/bin/*

RUN chown -R biop:biop /home/biop/ /home/biop/.cache    \
    && chmod -R u+rwX,g+rX,o-rwx /home/biop

#################################################################
# Container start
USER biop
WORKDIR /home/biop
RUN /opt/conda/envs/napari/bin/python -m ipykernel install --user --name=napari --display-name "Python (napari)"

#RUN conda init bash && echo "conda activate napari" >> ~/.bashrc
ENTRYPOINT ["jupyter"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]