ARG ALIAS=biop/
ARG BASE_IMAGE=0.1.0

FROM ${ALIAS}biop-vnc-base:${BASE_IMAGE}

USER root

RUN sudo apt-get update \
    && sudo apt-get install -y libegl1 libdbus-1-3 libxkbcommon-x11-0 \
     libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 \
     libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0 \
     x11-utils libxcb-cursor0 libopengl0 xterm\
    && apt-get autoremove --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/* \
    && find /var/log -type f -exec cp /dev/null \{\} \;


#############################################################################
# install napari
COPY /napari/env_napari_056.yml /tmp/env_napari.yml
RUN conda env update -n napari -f /tmp/env_napari.yml \
    && conda clean --all -f -y \
    && conda env export -n "biop" \
    && rm /tmp/env_napari.yml

# Create shortcut to start napari
COPY napari/napari-icon.ico /opt/napari/napari-icon.ico
COPY napari/start_napari.sh /opt/napari/start_napari.sh
RUN chmod +x /opt/napari/start_napari.sh \
    && chmod -R a+rwX /opt/napari/

# Create desktop icon with terminal emulator
RUN mkdir -p /home/biop/Desktop && chown -R biop:biop /home/biop/Desktop \
    && printf '[Desktop Entry]\nVersion=0.5.6\nName=napari\nGenericName=napari\nX-GNOME-FullName=napari\nComment=Scientific Image Analysis\nType=Application\nCategories=Education;Science;ImageProcessing;\nExec=xterm -e /opt/napari/start_napari.sh\nTryExec=/opt/napari/start_napari.sh\nTerminal=false\nStartupNotify=true\nIcon=/opt/napari/napari-icon.ico\nStartupWMClass=napari\n' > /home/biop/Desktop/napari.desktop \
    && chown -R biop:biop /home/biop \
    && chmod +x /home/biop/Desktop/napari.desktop


#################################################################
RUN chown -R biop:biop /home/biop/ \
&& chmod -R a+rwx /home/biop/ 

#################################################################
# Container start
USER biop
WORKDIR /home/biop
ENTRYPOINT ["/usr/local/bin/jupyter"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]


