# BASE 0.0.1 is working
ARG ALIAS=biop/
ARG NAPARI_VERSION=0.5.6

#FROM ${ALIAS}biop-vnc-base:${BASE_IMAGE} AS base
FROM ${ALIAS}biop-napari:${NAPARI_VERSION} AS base

USER root

##############################################################################
# install leonardo-napari
RUN  conda update -n base -c conda-forge conda  \
    && conda create --name leonardo python=3.9\
    && source activate leonardo \
    && pip install --upgrade pip \ 
    && pip install jax[cuda12] napari[all] leonardo_toolset[napari] napari-omero

## install napari-omero
# RUN source activate leonardo && pip install napari-omero

# Create shortcut to start leonardo-napari 
COPY icons/* /opt/icons/
RUN printf 'source activate leonardo\nnapari\n\$ read -rsp \$"Press enter to continue..."\n"Press enter to continue..."' > /opt/icons/start_leonardo.sh \
    && printf '[Desktop Entry]\nVersion=0.1.1\nName=leonardo-napari\nGenericName=leonardo\nX-GNOME-FullName=leonardo-napari\nComment=Scientific Image Analysis\nType=Application\nCategories=Education;Science;ImageProcessing;\nExec=xterm -e /opt/icons/start_leonardo.sh\nTryExec=xterm -e  /opt/icons/start_leonardo.sh\nTerminal=false\nStartupNotify=true\nIcon=/opt/icons/napari-icon.ico\nStartupWMClass=leonardo-napari\n' > /home/biop/Desktop/leonardo-napari.desktop \
    && chown -R biop:biop /home/biop /opt/icons/  \
    && chmod -R a+rwx /home/biop/ /opt/icons/
    
#################################################################
# Container start
USER biop
WORKDIR /home/biop
ENTRYPOINT ["/usr/local/bin/jupyter"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]