ARG ALIAS=biop/
ARG BASE_IMAGE=0.2.2
ARG CELLPOSESAM_VERSION=4.0.6

FROM ${ALIAS}biop-cellpose:${CELLPOSESAM_VERSION} AS cellposesam-image
FROM ${ALIAS}biop-vnc-base:${BASE_IMAGE}

USER root

# https://github.com/CellProfiler/CellProfiler/wiki/Conda-Installation
##############################################################################
# install cellprofiler
COPY cellprofiler/env_cellprofiler.yml /tmp/env_cellprofiler.yml
RUN conda update -n base -c conda-forge conda \ 
    && conda env update -n cellprofiler -f /tmp/env_cellprofiler.yml \
    && conda clean --all -f -y \
    && conda env export -n "biop" \
    && rm /tmp/env_cellprofiler.yml

# install cellprofiler plugins
RUN mkdir /opt/cellprofiler/ \
    && cd /opt/cellprofiler/ \
    && git clone https://github.com/CellProfiler/CellProfiler-plugins \
    && cd CellProfiler-plugins \
    && source activate cellprofiler \
    && pip install .[stardist] \
    && pip install .[cellpose] \
    && mkdir -p /home/biop/.python3/plugins \
    && mv /opt/cellprofiler/CellProfiler-plugins/active_plugins/* /home/biop/.python3/plugins/

# add cellpose models
COPY --from=cellposesam-image /home/biop/.cellpose/models/ /home/biop/.cellpose/models/

# create shortcut to start cellprofiler
COPY icons/CellProfiler.ico /opt/icons/CellProfiler.ico
RUN mkdir -p /home/biop/Desktop \
    # cellprofiler
    && printf 'source activate cellprofiler\nexport "PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True" && cellprofiler\n\$ read -rsp \$"Press enter to continue..."\n' > /opt/icons/start_cellprofiler.sh \
    && printf '[Desktop Entry]\nVersion=4.2.8\nName=cellprofiler\nGenericName=cellprofiler\nX-GNOME-FullName=cellprofiler\nComment=Scientific Image Analysis\nType=Application\nCategories=Education;Science;ImageProcessing;\nExec=/opt/icons/start_cellprofiler.sh\nTryExec=/opt/icons/start_cellprofiler.sh\nTerminal=true\nStartupNotify=true\nIcon=/opt/icons/CellProfiler.ico\nStartupWMClass=cellprofiler\n' > /home/biop/Desktop/cellprofiler.desktop \
    && chmod a+rwx /opt/icons/start_cellprofiler.sh \
    && chown -R biop:biop /opt/icons/ \
    && chmod +x /home/biop/Desktop/cellprofiler.desktop \
    && chown -R biop:biop /home/biop \
    && chmod -R a+rwx /home/biop/


#################################################################
# Container start
USER biop
WORKDIR /home/biop
ENTRYPOINT ["/usr/local/bin/jupyter"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]
