ARG ALIAS=biop/
ARG BASE_IMAGE=0.2.2
FROM ${ALIAS}biop-vnc-base:${BASE_IMAGE}

USER root

# https://github.com/CellProfiler/CellProfiler/wiki/Conda-Installation
##############################################################################
# install cellprofiler
COPY cellprofiler/env_cellprofiler.yml /tmp/env_cellprofiler.yml
RUN conda env update -n cellprofiler -f /tmp/env_cellprofiler.yml \
    && conda clean --all -f -y \
    && conda env export -n "biop" \
     && rm /tmp/env_cellprofiler.yml

# create shortcut to start cellprofiler
RUN mkdir /opt/cellprofiler
COPY cellprofiler/start_cellprofiler.sh /opt/cellprofiler/start_cellprofiler.sh
COPY cellprofiler/CellProfiler.ico /opt/cellprofiler/CellProfiler.ico


RUN chmod +x /opt/cellprofiler/start_cellprofiler.sh \
    && chown -R biop:biop /opt/cellprofiler/ 

RUN mkdir -p /home/biop/Desktop && chown -R biop:biop /home/biop/Desktop \
    && printf '[Desktop Entry]\nVersion=4.2.6\nName=cellprofiler\nGenericName=cellprofiler\nX-GNOME-FullName=cellprofiler\nComment=Scientific Image Analysis\nType=Application\nCategories=Education;Science;ImageProcessing;\nExec=/opt/cellprofiler/start_cellprofiler.sh\nTryExec=/opt/cellprofiler/start_cellprofiler.sh\nTerminal=true\nStartupNotify=true\nIcon=/opt/cellprofiler/CellProfiler.ico\nStartupWMClass=cellprofiler\n' > /home/biop/Desktop/cellprofiler.desktop \
    && chown -R biop:biop /home/biop \
    && chmod -R a+rwx /home/biop/


#################################################################
# Container start
USER biop
WORKDIR /home/biop
ENTRYPOINT ["/usr/local/bin/jupyter"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]
