ARG ALIAS=biop/
ARG BASE_IMAGE=0.2.2
FROM ${ALIAS}biop-vnc-base:${BASE_IMAGE}

USER root

# install cellpose and download models ( https://cellpose.readthedocs.io/en/latest/models.html )
COPY cellpose/env_cellpose.yml /tmp/env_cellpose.yml
RUN conda env update -n cellpose -f /tmp/env_cellpose.yml \
    && conda clean --all -f -y \
    && conda env export -n "biop" \ 
    && rm /tmp/env_cellpose.yml 

# download models
USER biop
COPY cellpose/download_all_models.py /home/biop/download_all_models.py
RUN source activate cellpose \
    && python /home/biop/download_all_models.py \
    && rm /home/biop/download_all_models.py

USER root
RUN chmod -R a+rwX /home/biop/ \
    && chown -R biop:biop /home/biop/

#################################################################
# Container start
USER biop
WORKDIR /home/biop
ENTRYPOINT ["/usr/local/bin/jupyter"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]
