ARG BASE_IMAGE=0.3.0
ARG ALIAS=biop/
## QuPath + InstanSeg / DJL
ARG QUPATH_VERSION=v0.7.0-only
ARG PYTORCH_VERSION=2.7.1
ARG DJL_VERSION=0.36.0
ARG CUDA_FLAVOR=cu126
# Additionnal python packages for QuPath extensions
ARG CELLPOSE_VERSION=3.1.1.1
ARG CELLPOSESAM_VERSION=4.2.1.1
ARG OMNI_VERSION=1.0.7-dev2
ARG SPOTIFLOW_VERSION=v0.6.4
ARG SAMAPI_VERSION=0.9.1 
ARG YOLO_VERSION=8.4.131


FROM ${ALIAS}biop-qupath:${QUPATH_VERSION} AS qupath-image
FROM ${ALIAS}biop-djl:${DJL_VERSION}-${CUDA_FLAVOR} as djl-image
FROM ${ALIAS}biop-cellpose:${CELLPOSE_VERSION} AS cellpose-image
FROM ${ALIAS}biop-cellpose:${CELLPOSESAM_VERSION} AS cellposesam-image
FROM ${ALIAS}biop-omni:${OMNI_VERSION} AS omnipose-image
FROM ${ALIAS}biop-spotiflow:${SPOTIFLOW_VERSION} AS spotiflow-image
FROM ${ALIAS}biop-samapi:${SAMAPI_VERSION} AS samapi-image
FROM ${ALIAS}biop-yolo:${YOLO_VERSION} AS yolo-image

FROM ${ALIAS}biop-vnc-base:${BASE_IMAGE}

USER root

################################################################# 
# Install QuPath 
COPY --from=qupath-image /opt/QuPath /opt/QuPath

#################################################################
# InstanSeg
# 
# To make InstanSeg and PyTorch via DJL working
# one needs to install a conda env with pytorch and download libdjl_torch.so 
# and to make QuPath start via a bash script that exports some path before starting QuPath
# see start_qp.sh in QuPath/prefs
COPY --from=djl-image /opt/conda/envs/djl /opt/conda/envs/djl
RUN mkdir -p /home/biop/.djl.ai/
COPY --from=djl-image --chown=biop:biop /home/biop/.djl.ai/ /home/biop/.djl.ai/


#################################################################
# Install cellpose and models
COPY --from=cellpose-image  /opt/conda/envs/cellpose /opt/conda/envs/cellpose
COPY --from=cellpose-image /home/biop/.cellpose/models/ /home/biop/.cellpose/models/
COPY --from=cellposesam-image  /opt/conda/envs/cellpose /opt/conda/envs/cellposesam
COPY --from=cellposesam-image /home/biop/.cellpose/models/ /home/biop/.cellpose/models/

# #################################################################
# Install spotiflow
COPY --from=spotiflow-image /opt/conda/envs/spotiflow /opt/conda/envs/spotiflow
COPY --from=spotiflow-image /home/biop/.spotiflow/models/ /home/biop/.spotiflow/models/

# #################################################################
# Install omnipose
COPY --from=omnipose-image /opt/conda/envs/omnipose /opt/conda/envs/omnipose

# #################################################################
# Install samapi
#
# add lib for wsl 
ENV LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH
# add samapi env 
COPY --from=samapi-image /opt/conda/envs/samapi /opt/conda/envs/samapi
# add models for samapi, SAM3 is not available for download (requires huggingface account) 
# so we don't include it in the docker image.
COPY --from=samapi-image /home/biop/.samapi/ /home/biop/.samapi/

# #################################################################
# Install yolo
COPY --from=yolo-image /opt/conda/envs/yolo /opt/conda/envs/yolo

##################################################################
# Update extensions from ZENODO repository (QuPath_Common_Data_0.7)
RUN rm -rf /opt/QuPath/QuPath_Common_Data_0.7/* \
    && wget -q  https://zenodo.org/records/22012154/files/QuPath_Common_Data_0.7.zip?download=1 -O ${TEMP_DIR}/QuPath_Common_Data_0.7.zip \
    && unzip ${TEMP_DIR}/QuPath_Common_Data_0.7.zip -d /opt/QuPath/QuPath_Common_Data_0.7 \
    && rm ${TEMP_DIR}/QuPath_Common_Data_0.7.zip \
    && chown -R biop:biop /opt/QuPath/QuPath_Common_Data_0.7 \
    && chmod -R a+rwx /opt/QuPath/QuPath_Common_Data_0.7

#################################################################
# Desktop icon + launcher scripts
# (COPY icons folder here because it may have been updated since
#  the base image was built)
COPY icons/ /opt/icons/
RUN mv /opt/icons/desktop-files/specific/qupath.desktop /home/biop/Desktop/ \
    && chmod 755 /home/biop/Desktop/qupath.desktop \
    && chown biop:biop /home/biop/Desktop/qupath.desktop \
    && mv /opt/icons/desktop-files/specific/samapi.desktop /home/biop/Desktop/ \
    && chmod 755 /home/biop/Desktop/qupath.desktop /home/biop/Desktop/samapi.desktop  \
    && chown biop:biop /home/biop/Desktop/qupath.desktop /home/biop/Desktop/samapi.desktop \
    && mv /opt/icons/scripts/* /usr/local/bin/ \
    && chmod 755 /usr/local/bin/*

#################################################################
# Prepare QuPath prefs (see QuPath_setPaths.groovy)
COPY QuPath/prefs/* /home/biop/tmp/
RUN chown -R biop:biop /home/biop \
    && chmod -R a+rwx /home/biop/

#################################################################
# Switch to end-user and finalize QuPath prefs
USER biop
RUN /opt/QuPath/bin/QuPath script '/home/biop/tmp/QuPath_setPaths.groovy' \
    && rm -rf /home/biop/tmp

WORKDIR /home/biop
ENTRYPOINT ["jupyter"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]
