ARG BASE_IMAGE=0.2.2
ARG ALIAS=biop/
ARG CELLPOSE_VERSION=3.1.1.1
ARG CELLPOSESAM_VERSION=4.0.6
ARG SPOTIFLOW_VERSION=v0.5.7


FROM ${ALIAS}biop-cellpose:${CELLPOSE_VERSION} AS cellpose-image
FROM ${ALIAS}biop-cellpose:${CELLPOSESAM_VERSION} AS cellposesam-image
FROM ${ALIAS}biop-spotiflow:${SPOTIFLOW_VERSION} AS spotiflow-image
FROM ${ALIAS}biop-vnc-base:${BASE_IMAGE}

ARG QP_VERSION=v0.6.0

USER root
#################################################################
# Install QuPath
# QuPath on Ubuntu can't use cellpose extension, needs to build from source ! 

# QuPath from source :
# https://qupath.readthedocs.io/en/stable/docs/reference/building.html
# install OpenJDK > 17 https://www.linuxcapable.com/how-to-install-openjdk-17-on-ubuntu-linux/
RUN apt-get update \
    && apt install openjdk-21-jdk -y

# install GPU by adding -Pcuda-redist to gradle command
RUN git clone  https://github.com/qupath/qupath.git --branch ${QP_VERSION} 
RUN cd qupath \
    && ./gradlew clean jpackage

RUN mv /home/biop/qupath/build/dist/QuPath/ /opt/QuPath \
    && chmod u+x /opt/QuPath/bin/QuPath \        
    && rm -rf /home/biop/qupath

# install Extensions
#TODO : reaplace with a zip 
RUN mkdir -p /opt/QuPath/QuPath_Common_Data_0.6 \
    && chown -R biop:biop /opt/QuPath/QuPath_Common_Data_0.6 \
    && chmod -R a+rwx /opt/QuPath/QuPath_Common_Data_0.6

# # TODO : discuss if we prepare unzip from zenodo, or if we update when container start via a git pull ... (less good for reproducibility but better to keep scripts up-to-date)
RUN wget -q  https://zenodo.org/records/16911894/files/QuPath_Common_Data_0.6.zip?download=1 -O ${TEMP_DIR}/QuPath_Common_Data_0.6.zip
RUN unzip ${TEMP_DIR}/QuPath_Common_Data_0.6.zip -d /opt/QuPath/QuPath_Common_Data_0.6 \
    && rm ${TEMP_DIR}/QuPath_Common_Data_0.6.zip 

# To make InstanSeg and PyTorch via DJL working  
# one needs to install a conda env with pytorch and download libdjl_torch.so 
# and to make QuPath start via a bash script that exports some path before starting QuPath
# see start_qp.sh in QuPath/prefs
RUN conda create --name djl --clone base \
    && source activate djl \
    && conda install pytorch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 pytorch-cuda=12.1 -c pytorch -c nvidia 

RUN mkdir -p /home/biop/.djl.ai/pytorch/2.5.1-cpu-linux-x86_64/ \
    && wget https://publish.djl.ai/pytorch/2.5.1/jnilib/0.33.0/linux-x86_64/cpu/libdjl_torch.so  -O /home/biop/.djl.ai/pytorch/2.5.1-cpu-linux-x86_64/0.33.0-libdjl_torch.so 

#################################################################
# Install cellpose and models
COPY --from=cellpose-image  /opt/conda/envs/cellpose /opt/conda/envs/cellpose
COPY --from=cellpose-image /home/biop/.cellpose/models/ /home/biop/.cellpose/models/

COPY --from=cellposesam-image  /opt/conda/envs/cellpose /opt/conda/envs/cellposesam
COPY --from=cellposesam-image /home/biop/.cellpose/models/ /home/biop/.cellpose/models/

#################################################################
# Install spotiflow
COPY --from=spotiflow-image /opt/conda/envs/spotiflow /opt/conda/envs/spotiflow
COPY --from=spotiflow-image /home/biop/.spotiflow/models/ /home/biop/.spotiflow/models/

# Prepare to set QP_prefs , see below `QuPath_setPaths.groovy`
COPY QuPath/prefs/* /home/biop/tmp/ 
# create icon on desktop
RUN mv /home/biop/tmp/start_qp.sh /opt/icons/start_qp.sh \
    && mkdir -p /home/biop/Desktop && chown -R biop:biop /home/biop/Desktop \
    && printf '[Desktop Entry]\nVersion=0.6.0\nName=qupath\nGenericName=QuPath\nX-GNOME-FullName=QuPath\nComment=Scientific Image Analysis\nType=Application\nCategories=Education;Science;ImageProcessing;\nExec=/opt/icons/start_qp.sh\nTryExec=/opt/icons/start_qp.sh\nTerminal=false\nStartupNotify=true\nIcon=/opt/QuPath/lib/QuPath.png\nStartupWMClass=QuPath' > /home/biop/Desktop/QuPath.desktop \
    && chown -R biop:biop /home/biop \
    && chmod +x /home/biop/Desktop/QuPath.desktop

RUN chown -R biop:biop /home/biop/ \
    && chmod -R a+rwx /home/biop/   

#################################################################
# Container start
USER biop
# here we import prefs in QuPath so that we can use the extensions at the first start ! 
RUN /opt/QuPath/bin/QuPath script '/home/biop/tmp/QuPath_setPaths.groovy' \
    && rm -rf /home/biop/tmp
WORKDIR /home/biop
ENTRYPOINT ["/usr/local/bin/jupyter"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]
