ARG BASE_IMAGE=0.2.1
ARG ALIAS=biop/
ARG CELLPOSE_VERSION=3.1.1.1


FROM ${ALIAS}biop-cellpose:${CELLPOSE_VERSION} AS cellpose-image
FROM ${ALIAS}biop-vnc-base:${BASE_IMAGE}

ARG QP_VERSION=v0.5.1

USER root
#################################################################
# Install QuPath
# QuPath on Ubuntu can't use cellpose extension, needs to build from source ! 

# QuPath from source :
# https://qupath.readthedocs.io/en/stable/docs/reference/building.html
# install OpenJDK > 17 https://www.linuxcapable.com/how-to-install-openjdk-17-on-ubuntu-linux/
RUN apt-get update \
    && apt install openjdk-17-jdk -y

# install GPU by adding -Pcuda-redist to gradle command
RUN git clone  https://github.com/qupath/qupath.git --branch ${QP_VERSION} 
RUN cd qupath \
    && ./gradlew clean jpackage

RUN mv /home/biop/qupath/build/dist/QuPath/ /opt/QuPath \
    && chmod u+x /opt/QuPath/bin/QuPath \        
    && rm -rf /home/biop/qupath

# # create icon
RUN mkdir -p /home/biop/Desktop && chown -R biop:biop /home/biop/Desktop \
    && printf '[Desktop Entry]\nVersion=0.5.1\nName=qupath\nGenericName=QuPath\nX-GNOME-FullName=QuPath\nComment=Scientific Image Analysis\nType=Application\nCategories=Education;Science;ImageProcessing;\nExec=/opt/QuPath/bin/QuPath\nTryExec=/opt/QuPath/bin/QuPath\nTerminal=false\nStartupNotify=true\nIcon=/opt/QuPath/lib/QuPath.png\nStartupWMClass=QuPath' > /home/biop/Desktop/QuPath.desktop \
    && chown -R biop:biop /home/biop \
    && chmod +x /home/biop/Desktop/QuPath.desktop

# install Extensions
RUN mkdir -p /opt/QuPath/QuPath_Common_Data_0.5 \
    && chown -R biop:biop /opt/QuPath/QuPath_Common_Data_0.5 \
    && chmod -R a+rwx /opt/QuPath/QuPath_Common_Data_0.5     

RUN wget -q https://zenodo.org/records/15040056/files/QuPath_Common_Data_0.5.zip?download=1 -O ${TEMP_DIR}/QuPath_Common_Data_0.5.zip \
    && unzip ${TEMP_DIR}/QuPath_Common_Data_0.5.zip -d /opt/QuPath/QuPath_Common_Data_0.5 \
    && rm ${TEMP_DIR}/QuPath_Common_Data_0.5.zip 

# Prepare to set QP_prefs , see below `QuPath_setPaths.groovy`
COPY QuPath/prefs/* /home/biop/tmp/

#################################################################
# Install cellpose and models
COPY --from=cellpose-image  /opt/conda/envs/cellpose /opt/conda/envs/cellpose
COPY --from=cellpose-image /home/biop/.cellpose/models/ /home/biop/.cellpose/models/
#RUN chmod -R a+rwX /home/biop/.cellpose  

RUN chown -R biop:biop /home/biop/ \
    && chmod -R a+rwx /home/biop/   

#################################################################
# Container start
USER biop
# here we import prefs in QuPath so that we can use the extensions at the first start ! 
RUN /opt/QuPath/bin/QuPath script '/home/biop/tmp/QuPath_setPaths.groovy' \
    && rm -rf /home/biop/tmp
WORKDIR /home/biop
ENTRYPOINT ["/usr/local/bin/jupyter"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]
