ARG BASE_IMAGE=0.3.1
ARG ALIAS=biop/
FROM ${ALIAS}biop-vnc-base:${BASE_IMAGE} as base

USER root

# install deepslice 
RUN conda create -n deepslice python=3.7 -y  \
    && conda run -n deepslice pip install deepslice==1.1.5 \
    && conda clean --all -f -y \
    && conda env export -n "biop" 


################################################################
# Container start
USER biop
WORKDIR /home/biop
ENTRYPOINT ["jupyter"]
#CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir="]