ARG BASE_IMAGE=0.3.1
ARG CELLPOSE_VERSION=3.1.1.1
ARG CELLPOSESAM_VERSION=4.2.1.1
ARG STARDIST_VERSION=0.9.2
ARG TRASCKASTRA_VERSION=v0.5.5
ARG ALIAS=biop/

FROM ${ALIAS}biop-cellpose:${CELLPOSE_VERSION} AS cellpose-image
FROM ${ALIAS}biop-cellpose:${CELLPOSESAM_VERSION} AS cellposesam-image
FROM ${ALIAS}biop-stardist:${STARDIST_VERSION} AS stardist-image
FROM ${ALIAS}biop-trackastra:${TRASCKASTRA_VERSION} AS trackastra-image

FROM ${ALIAS}biop-vnc-base:${BASE_IMAGE}

ENV OMEROIJ_VERSION=5.8.6
ENV SOC_VERSION=5.19.0

USER root

#################################################################
# Install Fiji
RUN wget -q https://mirrors.pasteur.fr/fiji/downloads/latest/fiji-latest-linux64-jdk.zip \
      && unzip -q fiji-latest-linux64-jdk.zip -d /opt/ \
      && rm fiji-latest-linux64-jdk.zip \
      && chmod -R a+rwX /opt/Fiji/

# Install Fiji plugins via update sites
ENV fiji=/opt/Fiji/fiji-linux-x64
ENV updateCommand="--update update"
ENV addCommand="--update add-update-sites" 
RUN ${fiji} ${updateCommand} \
    && ${fiji} ${addCommand}    "clij" "https://sites.imagej.net/clij/" \
                                "clij2" "https://sites.imagej.net/clij2/" \
                                "PTBIOP" "https://biop.epfl.ch/Fiji-Update" \ 
                                "IBMP-CNRS" "https://sites.imagej.net/Mutterer/" \
                                "3D ImageJ Suite" "https://sites.imagej.net/Tboudier/" \
                                "IJPB-plugins" "https://sites.imagej.net/IJPB-plugins/" \
                                "ilastik" "https://sites.imagej.net/Ilastik/" \
                                #"ImageScience" "https://sites.imagej.net/ImageScience/" \ 
                                "CSBDeep" "https://sites.imagej.net/CSBDeep/" \
                                "StarDist" "https://sites.imagej.net/StarDist/" \
                                "TrackMate-StarDist" "https://sites.imagej.net/TrackMate-StarDist/" \    
                                "TrackMate-TrackAstra" "https://sites.imagej.net/TrackMate-Trackastra/" \ 
                                "TrackMate-Cellpose" "https://sites.imagej.net/TrackMate-Cellpose/" \
                                "TensorFlow" "https://sites.imagej.net/TensorFlow/" \
                                "OMERO 5.5-5.6" "https://sites.imagej.net/OMERO-5.5-5.6/" \
                                "MiC mask comparator" "https://sites.imagej.net/MiC-mask-comparator/" \
                                "Fiji-Deconv" "https://sites.imagej.net/clijx-deconvolution/" \
                                "3Dscript" "https://romulus.oice.uni-erlangen.de/updatesite/" \
    && ${fiji} ${updateCommand} \
    && chmod -R a+rwX /opt/Fiji/

RUN mv /opt/icons/desktop-files/specific/fiji.desktop /home/biop/Desktop/ \
    && chmod 755 /home/biop/Desktop/fiji.desktop \
    && chown biop:biop /home/biop/Desktop/fiji.desktop

# # TF1.15 GPU (current default download of TF 1.12 CPU)
# RUN wget -q https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow_jni-gpu-linux-x86_64-1.15.0.tar.gz    \
#     && tar -C /opt/Fiji/lib/linux64/ -xzf libtensorflow_jni-gpu-linux-x86_64-1.15.0.tar.gz \
#     && rm libtensorflow_jni-gpu-linux-x86_64-1.15.0.tar.gz 

# Install omeroij
RUN wget -q https://github.com/ome/omero-insight/releases/download/v${OMEROIJ_VERSION}/omero_ij-${OMEROIJ_VERSION}-all.jar -O /opt/Fiji/plugins/omero_ij-${OMEROIJ_VERSION}-all.jar \
# ... simple-omero-client
    && wget -q https://github.com/GReD-Clermont/simple-omero-client/releases/download/${SOC_VERSION}/simple-omero-client-${SOC_VERSION}.jar -O /opt/Fiji/plugins/simple-omero-client-${SOC_VERSION}.jar \
# ... ThunderSTORM
    && wget -q https://github.com/zitmen/thunderstorm/releases/download/v1.3/Thunder_STORM.jar -O /opt/Fiji/plugins/Thunder_STORM.jar 

#ij2-LocalizeJ (depends from)
RUN wget -q https://repo1.maven.org/maven2/colt/colt/1.2.0/colt-1.2.0.jar -O /opt/Fiji/jars/colt-1.2.0.jar \
    && wget -q https://maven.imagej.net/content/repositories/releases/sc/fiji/imagescience/3.0.0/imagescience-3.0.0.jar -O /opt/Fiji/jars/imagescience-3.0.0.jar \
    && wget -q  https://github.com/ArneS70/ij2-LocalizeJ/raw/main/target/LocalizeJ-0.1.0-SNAPSHOT.jar -O /opt/Fiji/jars/LocalizeJ-0.1.0-SNAPSHOT.jar 

# DiAna plugin
RUN wget -q https://drive.google.com/file/d/1hkmM6kHMnPvwya26ogQsNaLI2AMVq_zN -O /opt/Fiji/plugins/DiAna_1.54.jar 

# MicrobeJ plugin (site down for maintenance)
# RUN wget -q http://www.microbej.com/version/13/p/1/MicrobeJ_.jar -O /opt/Fiji/plugins/MicrobeJ_.jar

#################################################################
# Install python envs
#
# cellpose and models
COPY --from=cellpose-image  /opt/conda/envs/cellpose /opt/conda/envs/cellpose
COPY --from=cellpose-image /home/biop/.cellpose/models/ /home/biop/.cellpose/models/
COPY --from=cellposesam-image  /opt/conda/envs/cellpose /opt/conda/envs/cellposesam
COPY --from=cellposesam-image /home/biop/.cellpose/models/ /home/biop/.cellpose/models/
#
RUN chmod -R a+rwX /home/biop/.cellpose  

# Install trackastra
COPY --from=trackastra-image  /opt/conda/envs/trackastra /opt/conda/envs/trackastra

# Install stardist 
COPY --from=stardist-image  /opt/conda/envs/stardist /opt/conda/envs/stardist

# to set prefs
COPY fiji/Fiji_setWrappersPaths.groovy /home/biop/tmp/Fiji_setWrappersPaths.groovy

RUN chown -R biop:biop /home/biop/ \
    && chmod -R a+rwx /home/biop/  

#################################################################
# Container start
USER biop
WORKDIR /home/biop
#RUN /opt/Fiji.app/ImageJ-linux64 --headless --run /home/biop/tmp/Fiji_setWrappersPaths.groovy \
#   && rm -rf /home/biop/tmp

ENTRYPOINT ["jupyter"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]