ARG BASE_IMAGE=0.3.1
ARG ALIAS=biop/

FROM ${ALIAS}biop-vnc-base:${BASE_IMAGE}

USER root

#################################################################
# Install Fiji
RUN wget -q https://mirrors.pasteur.fr/fiji/downloads/latest/fiji-latest-linux64-jdk.zip \
      && unzip -q fiji-latest-linux64-jdk.zip -d /opt/ \
      && rm fiji-latest-linux64-jdk.zip \
      && chmod -R a+rwX /opt/Fiji/

# Install Fiji plugins via update sites
ENV fiji=/opt/Fiji/fiji-linux-x64
ENV updateCommand="--update update"
ENV addCommand="--update add-update-sites" 
RUN ${fiji} ${updateCommand} \
    && ${fiji} ${addCommand}    "clij" "https://sites.imagej.net/clij/" \
                                "clij2" "https://sites.imagej.net/clij2/" \
                                "PTBIOP" "https://biop.epfl.ch/Fiji-Update" \ 
                                "IBMP-CNRS" "https://sites.imagej.net/Mutterer/" \
                                "3D ImageJ Suite" "https://sites.imagej.net/Tboudier/" \
                                "IJPB-plugins" "https://sites.imagej.net/IJPB-plugins/" \
                                "ilastik" "https://sites.imagej.net/Ilastik/" \
                                #"ImageScience" "https://sites.imagej.net/ImageScience/" \ 
                                "CSBDeep" "https://sites.imagej.net/CSBDeep/" \
                                "StarDist" "https://sites.imagej.net/StarDist/" \
                                "TrackMate-StarDist" "https://sites.imagej.net/TrackMate-StarDist/" \    
                                "TrackMate-TrackAstra" "https://sites.imagej.net/TrackMate-Trackastra/" \ 
                                "TrackMate-Cellpose" "https://sites.imagej.net/TrackMate-Cellpose/" \
                                "TensorFlow" "https://sites.imagej.net/TensorFlow/" \
                                "OMERO 5.5-5.6" "https://sites.imagej.net/OMERO-5.5-5.6/" \
                                "MiC mask comparator" "https://sites.imagej.net/MiC-mask-comparator/" \
                                "Fiji-Deconv" "https://sites.imagej.net/clijx-deconvolution/" \
                                "3Dscript" "https://romulus.oice.uni-erlangen.de/updatesite/" \
    && ${fiji} ${updateCommand} \
    && chmod -R a+rwX /opt/Fiji/


RUN mv /opt/icons/desktop-files/specific/fiji.desktop /home/biop/Desktop/ \
    && chmod 755 /home/biop/Desktop/fiji.desktop \
    && chown biop:biop /home/biop/Desktop/fiji.desktop


#################################################################
# Container start
USER biop
WORKDIR /home/biop
ENTRYPOINT ["jupyter"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]