ARG BASE_IMAGE=0.0.3

ARG ALIAS=biop/

# because COPY --from= doesn't support build-arg (https://github.com/docker/for-mac/issues/2155)
# we can still do a list of all sub-blocks here to be able to use them in the COPY --from=... below
# base needs to be last, Don't Ask Wky !  (I don't know) ! and it seems it need to be named 'base' , D.A:W.2 ! but it works !
ARG QUPATH_VERSION=v0.5.0
ARG ILASTIK_VERSION=1.4.0-gpu
ARG FIJI_VERSION=20240220
ARG CELLPOSE_VERSION=2.2.2
ARG DEVBIO_VERSION=0.10.1
ARG SAMAPI_VERSION=0.4.0
ARG EM_VERSION=0.2.3
ARG STARDIST_VERSION=0.8.5
ARG ABBA_VERSION=0.8.0
ARG CELLPROFILER_VERSION=4.2.6
ARG INKSCAPE_VERSION=0.0.1
ARG OMNI_VERSION=1.0.7-dev

FROM ${ALIAS}biop-qupath:${QUPATH_VERSION} as qupath-image
FROM ${ALIAS}biop-ilastik:${ILASTIK_VERSION} as ilastik-image
FROM ${ALIAS}biop-fiji:${FIJI_VERSION} as fiji-image
FROM ${ALIAS}biop-cellpose:${CELLPOSE_VERSION} as cellpose-image
FROM ${ALIAS}biop-devbio:${DEVBIO_VERSION} as devbio-image
FROM ${ALIAS}biop-samapi:${SAMAPI_VERSION} as samapi-image
FROM ${ALIAS}biop-empanada:${EM_VERSION} as empanada-image
FROM ${ALIAS}biop-stardist:${STARDIST_VERSION} as stardist-image
FROM ${ALIAS}biop-abba:${ABBA_VERSION} as abba-image
FROM ${ALIAS}biop-cellprofiler:${CELLPROFILER_VERSION} as cellprofiler-image
FROM ${ALIAS}biop-inkscape:${INKSCAPE_VERSION} as inkscape-image
FROm ${ALIAS}biop-omnipose:${OMNI_VERSION} as omnipose-image

FROM ${ALIAS}biop-vnc-base:${BASE_IMAGE} as base

USER root

RUN mkdir -p /home/biop/Desktop && chown -R biop:biop /home/biop/Desktop 

################################################################# 
# Install QuPath 
# 
COPY --from=qupath-image /opt/QuPath /opt/QuPath
COPY --from=qupath-image /home/biop/Desktop/QuPath.desktop  /home/biop/Desktop/QuPath.desktop

# install Extensions
COPY --from=qupath-image /opt/QuPath/QuPath_Common_Data_0.5 /opt/QuPath/QuPath_Common_Data_0.5  
RUN chown -R biop:biop /opt/QuPath/QuPath_Common_Data_0.5 \
    && chmod -R a+rwx /opt/QuPath/QuPath_Common_Data_0.5
    
# Prepare to set QP_prefs 
COPY QuPath/QuPath_setPaths.groovy /home/biop/tmp/QuPath_setPaths.groovy
COPY QuPath/qp_prefs.xml /home/biop/tmp/qp_prefs.xml
RUN chown -R biop:biop /home/biop/tmp
USER biop
# here we import prefs in QuPath so that we can use the extensions at the first start ! 
RUN /opt/QuPath/bin/QuPath script '/home/biop/tmp/QuPath_setPaths.groovy' 
# set back to root to continue installation
USER root
RUN rm -rf /home/biop/tmp 


#################################################################
# Install ilastik
COPY --from=ilastik-image /opt/ilastik /opt/ilastik
COPY --from=ilastik-image /home/biop/Desktop/ilastik.desktop /home/biop/Desktop/ilastik.desktop

#################################################################
# Install Fiji
COPY --from=fiji-image /opt/Fiji.app /opt/Fiji.app
COPY --from=fiji-image /home/biop/Desktop/Fiji.desktop /home/biop/Desktop/Fiji.desktop


#################################################################
# From here, we'll install different conda envs
# - cellpose
# - devbio
# - samapi
# - empanada
# - stardist, TODO make it work on RunAI
#
#################################################################
# Install cellpose and models
COPY --from=cellpose-image  /opt/conda/envs/cellpose /opt/conda/envs/cellpose
COPY --from=cellpose-image /home/biop/.cellpose/models/ /home/biop/.cellpose/models/
RUN chmod -R a+rwX /home/biop/.cellpose  

#################################################################
# Install devbio
COPY --from=devbio-image /opt/conda/envs/devbio /opt/conda/envs/devbio
# create shortcut to start devbio-napari
COPY --from=devbio-image /opt/devbio/ /opt/devbio/
COPY --from=devbio-image /home/biop/Desktop/devbio-napari.desktop  /home/biop/Desktop/devbio-napari.desktop 

#################################################################
# Install samapi
#
# add lib for wsl 
ENV LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH
# add samapi env 
COPY --from=samapi-image /opt/conda/envs/samapi /opt/conda/envs/samapi
# add models for samapi
COPY --from=samapi-image /home/biop/.samapi/ /home/biop/.samapi/
RUN chown -R biop:biop /home/biop/.samapi/ \
    && chmod -R a+rwX /home/biop/.samapi/ 
# create shortcut to start SAMAPI 
# because it's a QuPath extension I add (ico & sh) to the QuPath Common Data folder
# but we could also have them in /opt/samapi , as we have for empanada (see below)
COPY --from=samapi-image /opt/samapi/ /opt/samapi/
COPY --from=samapi-image /home/biop/Desktop/samapi.desktop /home/biop/Desktop/samapi.desktop

#################################################################
# Install empanada
#
# add empanada env
COPY --from=empanada-image /opt/conda/envs/empanada /opt/conda/envs/empanada
# add shortcut to start empanada
COPY --from=empanada-image /opt/empanada /opt/empanada
COPY --from=empanada-image /home/biop/Desktop/empanada.desktop /home/biop/Desktop/empanada.desktop
# TODO ? download model, it's a light one so we can download it on demand

#################################################################
# Install stardist
COPY --from=stardist-image /opt/conda/envs/stardist /opt/conda/envs/stardist

#################################################################
# Install abba
COPY --from=abba-image /home/biop/Desktop/abba.desktop  /home/biop/Desktop/abba.desktop 
COPY --from=abba-image /opt/abba /opt/abba
# set permissions , includes /opt/abba/cached_atlas/ 
RUN chown -R biop:biop /opt/abba/ \
    && chmod -R a+rwX /opt/abba/

# install abba_python env
COPY --from=abba-image /opt/conda/envs/abba_python/ /opt/conda/envs/abba_python/

# instal deepslice env
COPY --from=abba-image /opt/conda/envs/deepslice/  /opt/conda/envs/deepslice/

# and make deepslice_cli_v1.1.5.1.py executable
RUN chown biop:biop /opt/conda/envs/deepslice/ \
    && chmod a+rwx /opt/conda/envs/deepslice/deepslice_cli_v1.1.5.1.py 

# change permission of atlases 
# should be copy with the COPY above # COPY --from=abba-image /opt/conda/envs/deepslice/lib/site-packages/DeepSlice/metadata/weights/ /opt/conda/envs/deepslice/lib/python3.7/site-packages/DeepSlice/metadata/weights/
RUN chmod a+rwx /opt/conda/envs/deepslice/lib/python3.7/site-packages/DeepSlice/metadata/weights/xception_weights_tf_dim_ordering_tf_kernels.h5 \
    && chmod a+rwx /opt/conda/envs/deepslice/lib/python3.7/site-packages/DeepSlice/metadata/weights/Allen_Mixed_Best.h5 \
    && chmod a+rwx /opt/conda/envs/deepslice/lib/python3.7/site-packages/DeepSlice/metadata/weights/Synthetic_data_final.hdf5

# add elastix
COPY --from=abba-image /opt/elastix /opt/elastix
RUN chown -R biop:biop /opt/elastix \
    && chmod  a+rwx /opt/elastix/bin/elastix \
    && chmod  a+rwx /opt/elastix/bin/transformix  
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/elastix/lib

# Test if ABBA works again with all rights
RUN chown biop:biop /opt/Fiji.app/ \
    && chmod -R a+rwx /opt/Fiji.app/

# set FIJI prefs (elastix, cellpose , stardist), and adds text to set the path to atlases
COPY fiji/Fiji_setWrappersPaths.groovy /home/biop/tmp/Fiji_setWrappersPaths.groovy
RUN chown -R biop:biop /home/biop/tmp \
    && chmod -R a+rwX /home/biop/tmp

USER biop
RUN /opt/Fiji.app/ImageJ-linux64 --headless --run /home/biop/tmp/Fiji_setWrappersPaths.groovy
USER root
RUN rm -rf /home/biop/tmp

# a text file to specify where the atlases are
COPY --from=abba-image /opt/Fiji.app/plugins/BIOP/ABBA_Atlas_folder.txt /opt/Fiji.app/plugins/BIOP/ABBA_Atlas_folder.txt

#################################################################
# Install cellprofiler
COPY --from=cellprofiler-image /opt/conda/envs/cellprofiler /opt/conda/envs/cellprofiler
# create shortcut to start cellprofiler
COPY --from=cellprofiler-image /opt/cellprofiler /opt/cellprofiler
COPY --from=cellprofiler-image /home/biop/Desktop/cellprofiler.desktop /home/biop/Desktop/cellprofiler.desktop

#################################################################
# Add the inkscape-imagej-panel extension for inskcape
COPY --from=inkscape-image /home/biop/.config/inkscape/extensions/  /home/biop/.config/inkscape/extensions/ 

#################################################################
# Install omnipose
# https://omnipose.readthedocs.io/index.html
COPY --from=omnipose-image /opt/conda/envs/omnipose/ /opt/conda/envs/omnipose/
# TODO : add kernels! 
# TODO : add models!

#################################################################
# Jupyter kernels 
# 
# To make the different conda env available in jupyter
COPY jupyter/kernels/ /home/biop/.local/share/jupyter/kernels/

#################################################################
# final chown and chmod
RUN chown -R biop:biop /home/biop/ \
    && chmod -R a+rwx /home/biop/    


#################################################################
# # Install OpenCL ( for clij ... )
# Doesn't work (anymore) on local WSL2 but works on runai !!!
# see https://github.com/NVIDIA/nvidia-container-toolkit/issues/371
# We move at the end so that we can build a normal version and WSL one without it, as it is not supported anyway.
RUN apt-get update \
   && apt-get install -y nvidia-opencl-dev=11.5.1-1ubuntu1 \
    && apt remove -y libnvidia-compute-535-server \
    && apt-get autoremove --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/* \
    && find /var/log -type f -exec cp /dev/null \{\} \;

# # TODO : run Fiji to set prefs (done at the ABBA install, see below)

#################################################################
# Container start
USER biop
WORKDIR /home/biop
ENTRYPOINT ["/usr/local/bin/jupyter"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]


