ARG BASE_IMAGE=0.3.0
ARG QUPATH_VERSION=v0.7.0-only
ARG ALIAS=biop/

FROM ${ALIAS}biop-qupath:${QUPATH_VERSION} AS qupath-image
FROM ${ALIAS}biop-vnc-base:${BASE_IMAGE}

USER root

################################################################# 
# Install QuPath 
# 
COPY --from=qupath-image /opt/QuPath /opt/QuPath

# install samapi
RUN mamba create -n samapi -y python=3.12\
    && mamba run -n samapi pip install "torch==2.7.0" torchvision --index-url https://download.pytorch.org/whl/cu126 
    
RUN mamba run -n samapi pip install https://github.com/ksugar/samapi/archive/refs/tags/v0.7.1.tar.gz \
    && mamba clean -a -y

# add lib for wsl 
ENV LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH

# add models
RUN mkdir -p /home/biop/.cache/torch/hub/checkpoints/
# download from repo
RUN wget -q "https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth" -P /home/biop/.samapi/vit_h/
RUN wget -q "https://dl.fbaipublicfiles.com/segment_anything/sam_vit_l_0b3195.pth" -P /home/biop/.samapi/vit_l/
RUN wget -q "https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth" -P /home/biop/.samapi/vit_b/
RUN wget -q "https://github.com/ChaoningZhang/MobileSAM/raw/master/weights/mobile_sam.pt" -P /home/biop/.samapi/vit_t/

RUN wget -q "https://dl.fbaipublicfiles.com/segment_anything_2/072824/sam2_hiera_base_plus.pt" -P /home/biop/.samapi/sam2_bp/
RUN wget -q "https://dl.fbaipublicfiles.com/segment_anything_2/072824/sam2_hiera_small.pt" -P /home/biop/.samapi/sam2_s/
RUN wget -q "https://dl.fbaipublicfiles.com/segment_anything_2/072824/sam2_hiera_tiny.pt" -P /home/biop/.samapi/sam2_t/
RUN wget -q "https://dl.fbaipublicfiles.com/segment_anything_2/072824/sam2_hiera_large.pt" -P /home/biop/.samapi/sam2_l/

#################################################################
#TODO add sam3 models for samapi!!
#################################################################

# COPY pref files to set QuPath paths and extensions
COPY QuPath/prefs/* /home/biop/tmp/ 

# COPY icons folder because of updates since base image was created
COPY icons/ /opt/icons/
RUN mv /opt/icons/desktop-files/specific/qupath.desktop /home/biop/Desktop/ \
    && mv /opt/icons/desktop-files/specific/samapi.desktop /home/biop/Desktop/ \
    && chmod 755 /home/biop/Desktop/qupath.desktop /home/biop/Desktop/samapi.desktop  \
    && chown biop:biop /home/biop/Desktop/qupath.desktop /home/biop/Desktop/samapi.desktop \
    && mv /opt/icons/scripts/* /usr/local/bin/ \
    && chmod 755 /usr/local/bin/*

RUN chown -R biop:biop /home/biop/ \
    && chmod -R a+rwx /home/biop/

# #################################################################
# # Container start
USER biop
# # here we import prefs in QuPath so that we can use the extensions at the first start ! 
RUN /opt/QuPath/bin/QuPath script '/home/biop/tmp/QuPath_setPaths.groovy' \
    && rm -rf /home/biop/tmp
WORKDIR /home/biop
ENTRYPOINT ["jupyter"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]
