ARG BASE_IMAGE=0.3.1
ARG ALIAS=biop/
FROM ${ALIAS}biop-vnc-base:${BASE_IMAGE}

ARG ILASTIK_VERSION=1.4.2-gpu

USER root

#################################################################
# Install ilastik
RUN wget https://files.ilastik.org/ilastik-${ILASTIK_VERSION}-Linux.tar.bz2 -O ilastik-${ILASTIK_VERSION}-Linux.tar.bz2 

RUN tar -xf ilastik-${ILASTIK_VERSION}-Linux.tar.bz2 -C /opt/ \
      && mv /opt/ilastik-${ILASTIK_VERSION}-Linux /opt/ilastik \
      && rm ilastik-${ILASTIK_VERSION}-Linux.tar.bz2 \
      && chmod -R a+rwX /opt/ilastik/

COPY icons/ /opt/icons/
RUN mv /opt/icons/desktop-files/specific/ilastik.desktop /home/biop/Desktop/ \
    && chmod 755 /home/biop/Desktop/ilastik.desktop \
    && chown biop:biop /home/biop/Desktop/ilastik.desktop

RUN chmod -R a+rwX /home/biop/ \
    && chown -R biop:biop /home/biop/     

#################################################################
# Container start
USER biop
WORKDIR /home/biop
ENTRYPOINT ["jupyter"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]
