ARG BASE_IMAGE=0.0.1
FROM biop-vnc-base:${BASE_IMAGE}

USER root

##############################################################################
# install devbio-napari
COPY devbio/env_devbio.yml /tmp/env_devbio.yml
RUN conda env update -n devbio -f /tmp/env_devbio.yml \
    && conda clean --all -f -y \
    && conda env export -n "biop" \
     && rm /tmp/env_devbio.yml

#create shortcut to start devbio-napari 
COPY napari/napari-icon.ico /opt/devbio/napari-icon.ico
COPY devbio/start_devbio.sh /opt/devbio/start_devbio.sh
RUN chmod +x /opt/devbio/start_devbio.sh \
    && chmod -R a+rwX /opt/devbio/ 

RUN mkdir -p /home/biop/Desktop && chown -R biop:biop /home/biop/Desktop \
    && printf '[Desktop Entry]\nVersion=0.10.1\nName=devbio-napari\nGenericName=devbio-napari\nX-GNOME-FullName=devbio-napari\nComment=Scientific Image Analysis\nType=Application\nCategories=Education;Science;ImageProcessing;\nExec=/opt/devbio/start_devbio.sh\nTryExec=/opt/devbio/start_devbio.sh\nTerminal=true\nStartupNotify=true\nIcon=/opt/devbio/napari-icon.ico\nStartupWMClass=devbio-napari\n' > /home/biop/Desktop/devbio-napari.desktop \
    && chown -R biop:biop /home/biop \
    && chmod +x /home/biop/Desktop/devbio-napari.desktop 
    
#################################################################
# Container start
USER biop
WORKDIR /home/biop
ENTRYPOINT ["/usr/local/bin/jupyter"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]



