# BASE 0.0.1 is working
ARG ALIAS=biop/
ARG NAPARI_VERSION=0.5.6

#FROM ${ALIAS}biop-vnc-base:${BASE_IMAGE} AS base
FROM ${ALIAS}biop-napari:${NAPARI_VERSION} AS base

USER root

##############################################################################
# install devbio-napari
RUN mamba create --name devbio napari[all] python=3.9 devbio-napari=0.11.0 pyqt -c conda-forge -c pytorch \
    && conda clean --all -f -y

COPY icons/* /opt/icons/
RUN printf 'source activate devbio\nnaparia\n\$ read -rsp \$"Press enter to continue..."\n' > /opt/icons/start_devbio.sh \
    && printf '[Desktop Entry]\nVersion=0.11.0\nName=devbio-napari\nGenericName=devbio-napari\nX-GNOME-FullName=devbio-napari\nComment=Scientific Image Analysis\nType=Application\nCategories=Education;Science;ImageProcessing;\nExec=xterm -e /opt/icons/start_devbio.sh\nTryExec=xterm -e /opt/icons/start_devbio.sh\nTerminal=false\nStartupNotify=true\nIcon=/opt/icons/napari-icon.ico\nStartupWMClass=devbio-napari\n' > /home/biop/Desktop/devbio-napari.desktop \
    && chown -R biop:biop /home/biop/ /opt/icons/\
    && chmod -R a+rwx /home/biop/Desktop/ /opt/icons/
    
#################################################################
# Container start
USER biop
WORKDIR /home/biop
ENTRYPOINT ["/usr/local/bin/jupyter"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]



