ARG ALIAS=biop/
ARG BASE_IMAGE=0.2.2
FROM ${ALIAS}biop-vnc-base:${BASE_IMAGE}

USER root

##############################################################################
# install leonardo-napari
RUN  conda update -n base -c conda-forge conda  \
    && conda create --name empanada python=3.9\
    && source activate empanada \
    && pip install --upgrade pip \ 
    && pip install napari[all] empanada-napari==1.1.1 napari-omero

# create desktop shortcut the new way 
RUN mkdir /home/biop/.empanada/ \
    && wget "https://zenodo.org/record/6861565/files/MitoNet_v1_mini.pth?download=1" -O /home/biop/.empanada/MitoNet_v1_mini.pth \
    && wget "https://zenodo.org/record/6861565/files/MitoNet_v1.pth?download=1" -O /home/biop/.empanada/MitoNet_v1.pth

# Create shortcut to start napari
COPY icons/* /opt/icons/
RUN printf 'source activate empanada\nnapari\n\$ read -rsp \$"Press enter to continue..."' > /opt/icons/start_empanada.sh \
    && printf '[Desktop Entry]\nVersion=1.1.1\nName=empanada\nGenericName=empanada\nX-GNOME-FullName=empanada\nComment=Scientific Image Analysis\nType=Application\nCategories=Education;Science;ImageProcessing;\nExec=/opt/icons/start_empanada.sh\nTryExec=/opt/icons/start_empanada.sh\nTerminal=true\nStartupNotify=true\nIcon=/opt/icons/empanada_icon.png\nStartupWMClass=empanada\n' > /home/biop/Desktop/empanada.desktop \
    && chown -R biop:biop /home/biop /opt/icons/ \
    && chmod -R +rwx /home/biop/Desktop/empanada.desktop /opt/icons/


#################################################################
# Container start
USER biop
WORKDIR /home/biop
ENTRYPOINT ["/usr/local/bin/jupyter"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]
