ARG BASE_IMAGE=0.1.0
ARG ALIAS=biop/
FROM ${ALIAS}biop-vnc-base:${BASE_IMAGE}

USER root

#################################################################
# Install Inkscape extension 
RUN sudo apt-get update -y \
    && sudo apt-get install inkscape -y 

#################################################################
# and the inkscape-imagej-panel https://gitlab.com/doctormo/inkscape-imagej-panel/
RUN wget https://gitlab.com/doctormo/inkscape-imagej-panel/-/archive/master/inkscape-imagej-panel-master.zip
RUN unzip inkscape-imagej-panel-master.zip \
    && mkdir -p /home/biop/.config/inkscape/extensions/ \
    && cp -r inkscape-imagej-panel-master/* /home/biop/.config/inkscape/extensions/ \
    && rm -rf inkscape-imagej-panel-master.zip \
    && rm -rf inkscape-imagej-panel-master/

#################################################################
# Inkscape preferences with path to ImageJ, devbio conda env already set up
# won't work ofr this image that does not have devbio nor Fiji
COPY inkscape/preferences.xml /home/biop/.config/inkscape/preferences.xml

RUN chown -R biop:biop /home/biop/ \
    && chmod -R a+rwx /home/biop/    

#################################################################
# Container start
USER biop
WORKDIR /home/biop
ENTRYPOINT ["/usr/local/bin/jupyter"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]