ARG BASE_IMAGE=0.2.1

ARG FIJI_VERSION=20250319

ARG ALIAS=biop/

FROM ${ALIAS}biop-fiji:${FIJI_VERSION} AS fiji-image

FROM ${ALIAS}biop-vnc-base:${BASE_IMAGE}

USER root

#################################################################
# Install Inkscape
# No need as it's installed in the base image now

#################################################################
# and the inkscape-imagej-panel https://gitlab.com/doctormo/inkscape-imagej-panel/
RUN wget https://gitlab.com/doctormo/inkscape-imagej-panel/-/archive/master/inkscape-imagej-panel-master.zip
RUN unzip inkscape-imagej-panel-master.zip \
    && mkdir -p /home/biop/.config/inkscape/extensions/ \
    && cp -r inkscape-imagej-panel-master/* /home/biop/.config/inkscape/extensions/ \
    && rm -rf inkscape-imagej-panel-master.zip \
    && rm -rf inkscape-imagej-panel-master/

#################################################################
# Inkscape preferences with path to ImageJ, inkscape conda env already set up
COPY inkscape/preferences.xml /home/biop/.config/inkscape/preferences.xml

#################################################################
# Install SimpInkScr extension
# RUN cd $HOME/.config/inkscape/extensions/ && git clone https://github.com/spakin/SimpInkScr.git
RUN wget https://github.com/spakin/SimpInkScr/releases/download/v5.0.0/simple_inkscape_scripting.zip
RUN unzip simple_inkscape_scripting.zip \
    && cp -r simple_inkscape_scripting/* /home/biop/.config/inkscape/extensions/ \
    && rm -rf simple_inkscape_scripting.zip \
    && rm -rf simple_inkscape_scripting/

#################################################################
# Install Fiji    
COPY --from=fiji-image /opt/Fiji.app /opt/Fiji.app
RUN printf '[Desktop Entry]\nVersion=1.0\nName=ImageJ\nGenericName=ImageJ\nX-GNOME-FullName=ImageJ\nComment=Scientific Image Analysis\nType=Application\nCategories=Education;Science;ImageProcessing;\nExec=/opt/Fiji.app/ImageJ-linux64 %F\nTryExec=/opt/Fiji.app/ImageJ-linux64\nTerminal=false\nStartupNotify=true\nMimeType=image/*;\nIcon=/opt/Fiji.app/images/icon.png\nStartupWMClass=net-imagej-launcher-ClassLauncher\n' > /home/biop/Desktop/Fiji.desktop
##############################################################################
# install inkscape_modules environment
COPY inkscape/env_inkscape.yml /tmp/env_inkscape.yml
RUN conda env update -n inkscape_modules -f /tmp/env_inkscape.yml \
    && conda clean --all -f -y \
    && conda env export -n "biop" \
     && rm /tmp/env_inkscape.yml


RUN chown -R biop:biop /home/biop/ /opt/Fiji.app \
    && chmod -R a+rwx /home/biop/  /opt/Fiji.app  

#################################################################
# Container start
USER biop
WORKDIR /home/biop
ENTRYPOINT ["/usr/local/bin/jupyter"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]