ARG BASE_IMAGE=0.2.1
ARG ALIAS=biop/
FROM ${ALIAS}biop-vnc-base:${BASE_IMAGE}

USER root

#################################################################
# Install Inkscape extension 
RUN sudo apt-get update -y \
    && sudo apt-get install software-properties-common -y \
    && sudo apt-get update -y \
    && sudo add-apt-repository ppa:inkscape.dev/stable \
    && sudo apt-get update -y \
    && sudo apt-get install inkscape -y 

#################################################################
# and the inkscape-imagej-panel https://gitlab.com/doctormo/inkscape-imagej-panel/
RUN wget https://gitlab.com/doctormo/inkscape-imagej-panel/-/archive/master/inkscape-imagej-panel-master.zip
RUN unzip inkscape-imagej-panel-master.zip \
    && mkdir -p /home/biop/.config/inkscape/extensions/ \
    && cp -r inkscape-imagej-panel-master/* /home/biop/.config/inkscape/extensions/ \
    && rm -rf inkscape-imagej-panel-master.zip \
    && rm -rf inkscape-imagej-panel-master/

#################################################################
# Inkscape preferences with path to ImageJ, inkscape conda env already set up
# won't work ofr this image that does not have inkscape nor Fiji
COPY inkscape/preferences.xml /home/biop/.config/inkscape/preferences.xml


#################################################################
# Install SimpInkScr extension
# RUN cd $HOME/.config/inkscape/extensions/ && git clone https://github.com/spakin/SimpInkScr.git
RUN wget https://github.com/spakin/SimpInkScr/releases/download/v5.0.0/simple_inkscape_scripting.zip
RUN unzip simple_inkscape_scripting.zip \
    && cp -r simple_inkscape_scripting/* /home/biop/.config/inkscape/extensions/ \
    && rm -rf simple_inkscape_scripting.zip \
    && rm -rf simple_inkscape_scripting/

##############################################################################
# install inkscape_modules environment
COPY inkscape/env_inkscape.yml /tmp/env_inkscape.yml
RUN conda env update -n inkscape_modules -f /tmp/env_inkscape.yml \
    && conda clean --all -f -y \
    && conda env export -n "biop" \
     && rm /tmp/env_inkscape.yml


RUN chown -R biop:biop /home/biop/ \
    && chmod -R a+rwx /home/biop/    

#################################################################
# Container start
USER biop
WORKDIR /home/biop
ENTRYPOINT ["/usr/local/bin/jupyter"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]